### ISSUE TITLE
$(Rev:r) not resolved

### ISSUE THREAD

**Issue by chjordanTE** [RezStream/rezStream-azure-devops-tasks#7]
Hi, I think there is an issue if I'm using the $(Rev:r) function in the pipeline. Cause if i run the app, it will not resolve the number behind the $(Rev:r) variable. All other local variables are well. Here are my configuration and results:

Variable declaration inside YAML Skript:
![image](https://user-images.githubusercontent.com/90695301/133252972-a2bca00f-dd89-4e64-b964-38e912e4ee97.png)

YAML Skript Call:
![image](https://user-images.githubusercontent.com/90695301/133253019-af110076-db12-492c-a9cd-ca3d8d9a8d42.png)

Output (the file which should be manipulated)
![image](https://user-images.githubusercontent.com/90695301/133252878-2e35b19d-2684-465f-9e9a-1b5e1807811d.png)

**Comment by aarondandy** [comment]
I think this is more of a azure devops yaml issue. From what I remember, `$(Rev:r)` and some other versioning related variables only work within the build number variable which I think is the name property on the yaml document. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml .

**Comment by chjordanTE** [comment]
ok, I see and agree with you.... it's the same with other tools too (e.g. "Replace Tokens")... 

can you please introduce me how I can place this to DevOps Team? or is there any option to force the variable (or resolve the number) on job initialization?

**Comment by chjordanTE** [comment]
ok, I think I found the Developer Community. Thanks

**Comment by aarondandy** [comment]
Well here are some ideas I have:

Set the build number in the `name:` property and then reference the build number via `variables: VersionNumber: $(Build.BuildNumber)` . This might work out for you?

My solution to this problem was to not have it. For applications (I assume the context here is an application or service) my opinion is that semver is not an appropriate versioning scheme. That isn't to say it does not work, obviously anything that increments will work, but I don't think it is the best fit. Instead I like to just use dates for application versioning because that is often what I actually care about.

```
variables:
  version.number: $[format('{0:yyMM}.{0:ddHH}.{1}', pipeline.startTime, variables['Build.BuildID'])]
  version.suffix: $[replace(variables['Build.SourceBranchName'], '/', '-')]
```

That is about all I can offer you. Working with pipelines can definitely be frustrating, good luck!
